<<<<<<< HEAD
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
=======
index:
    path: /
    controller: App\Controller\HomeController::home
>>>>>>> 334cbdd17674032bccd06a53fbe23d26723f3213
